### ISSUE TITLE
Problems in configs/*.yaml

### ISSUE THREAD

**Issue by LYB926** [Cynicarlos/RetinexRawMamba#3]
Dear author,

When I try to run test_mcr.py, I get the error ```data_dir: /data/dataset/Carlos/MCR``` not found.
This is due to the incorrect location of the datasets in ```configs/*.yaml```(Line 16). 

For the MCR dataset: data_dir: ```/data/dataset/Carlos/MCR``` ->   ```data_dir: ./datasets/MCR``` will be fine.

Wishing you good news about your paper!

**Comment by Cynicarlos** [comment]
Thank you for reminding me,  and you are totally right about this problem.  Actually, I guess most people prefer to keep their datasets in a folder outside of the project, so I didn't change the path. And all thanks to your lucky words for the paper!
